
spring:
  application:
    name: mmall
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://192.168.156.4:3306/mall?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    password: mall
    username: mall
    #druid数据库配置
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config


#redis
  redis:
    host: 192.168.156.4
    port: 6379
    timeout: 10000ms
    database: 0
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms

# logback日志
logging:
  config: classpath:log/logback-spring.xml

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mmall.pojo


# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



server:
  port: 8080